### PR TITLE
Further whitelist tweaks

### PR DESCRIPTION
**Pull request by 62832**
New whitelisted book (Evilcraft's _Origins of Darkness_) for 1.18 and a couple of 1.16 mod books, plus a new list of mod aliases for mods at least currently out for 1.18.

May be worth having a pinned issue dedicated to default whitelist/blacklist additions to prevent these pulls from being too spammy.

### CODE REVIEW

**Comment by EccentricVamp** [comment]
Looks good to me.

Are you thinking the pinned issue would be referenced in comments of each pull request?

I don't disagree; I'm just trying to understand how it would reduce spammyness.

**Comment by EccentricVamp** [comment]
Hmm. Been thinking of enabling GitHub Discussions for feature requests and such. I'll experiment with that a bit. Might make a discussion category for default white/black list changes. Either way, I'll merge this request now.

**Comment by EccentricVamp** [comment]
I didn't spot this until after I merged, but the separator for aliases is `=` (not `:`). Small thing, but it would've broken the default config.

Do you think `:` would be a more intuitive separator? I could change it pretty easily, but I worry that people (including myself) would get it confused with resource locations which are usually of the form `<namespace>:<path>`. Whereas aliases should be of the form `<namespace>=<other_namespace>`

**Comment by 62832** [comment]
I'll be honest, that was just me being a twat editing the config directly via GitHub rather than my IDE and forgetting to read the mod alias section properly before reworking it.

I have no issue with `=` being the separator for the alias section as long as people don't just assume the because one section uses `:` the other ones must also all do the same.

**Pull request merged**
